<?php
namespace Brother\MapBundle\Model\Options;

/**
 * https://tech.yandex.ru/maps/doc/jsapi/2.0/ref/reference/option.presetStorage-docpage/
 * Class PresetStorage
 * @package Brother\MapBundle\Model\Options
 */
class PresetStorage
{

//Метки без содержимого
    public static $icons = array(
        'twirl#blackIcon' => 'blackIcon',
        'twirl#blueIcon' => 'blueIcon',
        'twirl#brownIcon' => 'brownIcon',
        'twirl#darkblueIcon' => 'darkblueIcon',
        'twirl#darkgreenIcon' => 'darkgreenIcon',
        'twirl#darkorangeIcon' => 'darkorangeIcon',
        'twirl#greenIcon' => 'greenIcon',
        'twirl#greyIcon' => 'greyIcon',
        'twirl#lightblueIcon' => 'lightblueIcon',
        'twirl#nightIcon' => 'nightIcon',
        'twirl#orangeIcon' => 'orangeIcon',
        'twirl#pinkIcon' => 'pinkIcon',
        'twirl#redIcon' => 'redIcon',
        'twirl#violetIcon' => 'violetIcon',
        'twirl#whiteIcon' => 'whiteIcon',
        'twirl#yellowIcon' => 'yellowIcon',
    );
//Метки без содержимого с точкой в центре
    public static $dotIcons = array(
        'twirl#blackDotIcon' => 'blackDotIcon',
        'twirl#blueDotIcon' => 'blueDotIcon',
        'twirl#brownDotIcon' => 'brownDotIcon',
        'twirl#darkblueDotIcon' => 'darkblueDotIcon',
        'twirl#darkgreenDotIcon' => 'darkgreenDotIcon',
        'twirl#darkorangeDotIcon' => 'darkorangeDotIcon',
        'twirl#greenDotIcon' => 'greenDotIcon',
        'twirl#greyDotIcon' => 'greyDotIcon',
        'twirl#lightblueDotIcon' => 'lightblueDotIcon',
        'twirl#nightDotIcon' => 'nightDotIcon',
        'twirl#orangeDotIcon' => 'orangeDotIcon',
        'twirl#pinkDotIcon' => 'pinkDotIcon',
        'twirl#redDotIcon' => 'redDotIcon',
        'twirl#violetDotIcon' => 'violetDotIcon',
        'twirl#whiteDotIcon' => 'whiteDotIcon',
        'twirl#yellowDotIcon' => 'yellowDotIcon',
    );
//Метки с текстом (иконки тянутся под контент)
    static public $stretchIcons = array(
        'twirl#blackStretchyIcon' => 'blackStretchyIcon',
        'twirl#blueStretchyIcon' => 'blueStretchyIcon',
        'twirl#brownStretchyIcon' => 'brownStretchyIcon',
        'twirl#darkblueStretchyIcon' => 'darkblueStretchyIcon',
        'twirl#darkgreenStretchyIcon' => 'darkgreenStretchyIcon',
        'twirl#darkorangeStretchyIcon' => 'darkorangeStretchyIcon',
        'twirl#greenStretchyIcon' => 'greenStretchyIcon',
        'twirl#greyStretchyIcon' => 'greyStretchyIcon',
        'twirl#lightblueStretchyIcon' => 'lightblueStretchyIcon',
        'twirl#nightStretchyIcon' => 'nightStretchyIcon',
        'twirl#orangeStretchyIcon' => 'orangeStretchyIcon',
        'twirl#pinkStretchyIcon' => 'pinkStretchyIcon',
        'twirl#redStretchyIcon' => 'redStretchyIcon',
        'twirl#violetStretchyIcon' => 'violetStretchyIcon',
        'twirl#whiteStretchyIcon' => 'whiteStretchyIcon',
        'twirl#yellowStretchyIcon' => 'yellowStretchyIcon',
    );
//Стандартные значки (пиктограммы)
    public static $thematicIcons = array(
        'twirl#airplaneIcon' => 'airplaneIcon',
        'twirl#anchorIcon' => 'anchorIcon',
        'twirl#arrowDownLeftIcon' => 'arrowDownLeftIcon',
        'twirl#arrowDownRightIcon' => 'arrowDownRightIcon',
        'twirl#arrowLeftIcon' => 'arrowLeftIcon',
        'twirl#arrowRightIcon' => 'arrowRightIcon',
        'twirl#arrowUpIcon' => 'arrowUpIcon',
        'twirl#badmintonIcon' => 'badmintonIcon',
        'twirl#bankIcon' => 'bankIcon',
        'twirl#barberShopIcon' => 'barberShopIcon',
        'twirl#barIcon' => 'barIcon',
        'twirl#bicycleIcon' => 'bicycleIcon',
        'twirl#bowlingIcon' => 'bowlingIcon',
        'twirl#buildingsIcon' => 'buildingsIcon',
        'twirl#busIcon' => 'busIcon',
        'twirl#cafeIcon' => 'cafeIcon',
        'twirl#campingIcon' => 'campingIcon',
        'twirl#carIcon' => 'carIcon',
        'twirl#cellularIcon' => 'cellularIcon',
        'twirl#cinemaIcon' => 'cinemaIcon',
        'twirl#downhillSkiingIcon' => 'downhillSkiingIcon',
        'twirl#dpsIcon' => 'dpsIcon',
        'twirl#dryCleanerIcon' => 'dryCleanerIcon',
        'twirl#electricTrainIcon' => 'electricTrainIcon',
        'twirl#factoryIcon' => 'factoryIcon',
        'twirl#fishingIcon' => 'fishingIcon',
        'twirl#gasStationIcon' => 'gasStationIcon',
        'twirl#gymIcon' => 'gymIcon',
        'twirl#hospitalIcon' => 'hospitalIcon',
        'twirl#houseIcon' => 'houseIcon',
        'twirl#keyMasterIcon' => 'keyMasterIcon',
        'twirl#mailPostIcon' => 'mailPostIcon',
        'twirl#metroKievIcon' => 'metroKievIcon',
        'twirl#metroMoscowIcon' => 'metroMoscowIcon',
        'twirl#metroStPetersburgIcon' => 'metroStPetersburgIcon',
        'twirl#metroYekaterinburgIcon' => 'metroYekaterinburgIcon',
        'twirl#motobikeIcon' => 'motobikeIcon',
        'twirl#mushroomIcon' => 'mushroomIcon',
        'twirl#phoneIcon' => 'phoneIcon',
        'twirl#photographerIcon' => 'photographerIcon',
        'twirl#pingPongIcon' => 'pingPongIcon',
        'twirl#restaurauntIcon' => 'restaurauntIcon',
        'twirl#shipIcon' => 'shipIcon',
        'twirl#shopIcon' => 'shopIcon',
        'twirl#skatingIcon' => 'skatingIcon',
        'twirl#skiingIcon' => 'skiingIcon',
        'twirl#smartphoneIcon' => 'smartphoneIcon',
        'twirl#stadiumIcon' => 'stadiumIcon',
        'twirl#storehouseIcon' => 'storehouseIcon',
        'twirl#swimmingIcon' => 'swimmingIcon',
        'twirl#tailorShopIcon' => 'tailorShopIcon',
        'twirl#tennisIcon' => 'tennisIcon',
        'twirl#theaterIcon' => 'theaterIcon',
        'twirl#tireIcon' => 'tireIcon',
        'twirl#trainIcon' => 'trainIcon',
        'twirl#tramwayIcon' => 'tramwayIcon',
        'twirl#trolleybusIcon' => 'trolleybusIcon',
        'twirl#truckIcon' => 'truckIcon',
        'twirl#turnLeftIcon' => 'turnLeftIcon',
        'twirl#turnRightIcon' => 'turnRightIcon',
        'twirl#wifiIcon' => 'wifiIcon',
        'twirl#wifiLogoIcon' => 'wifiLogoIcon',
        'twirl#workshopIcon' => 'workshopIcon',
    );
//Значки кластеров
    public static $clasters = array(
        'twirl#blackClusterIcons' => 'blackClusterIcons',
        'twirl#blueClusterIcons' => 'blueClusterIcons',
        'twirl#brownClusterIcons' => 'brownClusterIcons',
        'twirl#darkblueClusterIcons' => 'darkblueClusterIcons',
        'twirl#darkgreenClusterIcons' => 'darkgreenClusterIcons',
        'twirl#darkorangeClusterIcons' => 'darkorangeClusterIcons',
        'twirl#greenClusterIcons' => 'greenClusterIcons',
        'twirl#greyClusterIcons' => 'greyClusterIcons',
        'twirl#invertedBlackClusterIcons' => 'invertedBlackClusterIcons',
        'twirl#invertedBlueClusterIcons' => 'invertedBlueClusterIcons',
        'twirl#invertedBrownClusterIcons' => 'invertedBrownClusterIcons',
        'twirl#invertedDarkblueClusterIcons' => 'invertedDarkblueClusterIcons',
        'twirl#invertedDarkgreenClusterIcons' => 'invertedDarkgreenClusterIcons',
        'twirl#invertedDarkorangeClusterIcons' => 'invertedDarkorangeClusterIcons',
        'twirl#invertedGreenClusterIcons' => 'invertedGreenClusterIcons',
        'twirl#invertedGreyClusterIcons' => 'invertedGreyClusterIcons',
        'twirl#invertedLightblueClusterIcons' => 'invertedLightblueClusterIcons',
        'twirl#invertedNightClusterIcons' => 'invertedNightClusterIcons',
        'twirl#invertedOrangeClusterIcons' => 'invertedOrangeClusterIcons',
        'twirl#invertedPinkClusterIcons' => 'invertedPinkClusterIcons',
        'twirl#invertedRedClusterIcons' => 'invertedRedClusterIcons',
        'twirl#invertedVioletClusterIcons' => 'invertedVioletClusterIcons',
        'twirl#invertedWhiteClusterIcons' => 'invertedWhiteClusterIcons',
        'twirl#invertedYellowClusterIcons' => 'invertedYellowClusterIcons',
        'twirl#lightblueClusterIcons' => 'lightblueClusterIcons',
        'twirl#nightClusterIcons' => 'nightClusterIcons',
        'twirl#orangeClusterIcons' => 'orangeClusterIcons',
        'twirl#pinkClusterIcons' => 'pinkClusterIcons',
        'twirl#redClusterIcons' => 'redClusterIcons',
        'twirl#violetClusterIcons' => 'violetClusterIcons',
        'twirl#whiteClusterIcons' => 'whiteClusterIcons',
        'twirl#yellowClusterIcons' => 'yellowClusterIcons',
    );
} 